[[Iron]]
"Exchange Ratio" = [
    "1/2 ton",
    "10 pounds",
]
"Good Name" = "Tea"

[[Iron]]
"Exchange Ratio" = [
    "1/2 ton",
    "1 quarter",
]
"Good Name" = "Wheat"

[[Iron]]
"Exchange Ratio" = [
    "1/2 ton",
    "x quantity",
]
"Good Name" = "Good A"

[[Iron]]
"Exchange Ratio" = [
    "1/2 ton",
    "1 piece",
]
"Good Name" = "Shirt"

[[Iron]]
"Exchange Ratio" = [
    "1/2 ton",
    "2 ounces",
]
"Good Name" = "Gold"

[[Iron]]
"Exchange Ratio" = [
    "1/2 ton",
    "40 pounds",
]
"Good Name" = "Coffee"

[[Iron]]
"Exchange Ratio" = [
    "1/2 ton",
    "20 yards",
]
"Good Name" = "Linen"

[[Tea]]
"Exchange Ratio" = [
    "10 pounds",
    "1/2 ton",
]
"Good Name" = "Iron"

[[Tea]]
"Exchange Ratio" = [
    "10 pounds",
    "1 quarter",
]
"Good Name" = "Wheat"

[[Tea]]
"Exchange Ratio" = [
    "10 pounds",
    "x quantity",
]
"Good Name" = "Good A"

[[Tea]]
"Exchange Ratio" = [
    "10 pounds",
    "1 piece",
]
"Good Name" = "Shirt"

[[Tea]]
"Exchange Ratio" = [
    "10 pounds",
    "2 ounces",
]
"Good Name" = "Gold"

[[Tea]]
"Exchange Ratio" = [
    "10 pounds",
    "40 pounds",
]
"Good Name" = "Coffee"

[[Tea]]
"Exchange Ratio" = [
    "10 pounds",
    "20 yards",
]
"Good Name" = "Linen"

[[Wheat]]
"Exchange Ratio" = [
    "1 quarter",
    "1/2 ton",
]
"Good Name" = "Iron"

[[Wheat]]
"Exchange Ratio" = [
    "1 quarter",
    "10 pounds",
]
"Good Name" = "Tea"

[[Wheat]]
"Exchange Ratio" = [
    "1 quarter",
    "x quantity",
]
"Good Name" = "Good A"

[[Wheat]]
"Exchange Ratio" = [
    "1 quarter",
    "1 piece",
]
"Good Name" = "Shirt"

[[Wheat]]
"Exchange Ratio" = [
    "1 quarter",
    "2 ounces",
]
"Good Name" = "Gold"

[[Wheat]]
"Exchange Ratio" = [
    "1 quarter",
    "40 pounds",
]
"Good Name" = "Coffee"

[[Wheat]]
"Exchange Ratio" = [
    "1 quarter",
    "20 yards",
]
"Good Name" = "Linen"

[["Good A"]]
"Exchange Ratio" = [
    "x quantity",
    "1/2 ton",
]
"Good Name" = "Iron"

[["Good A"]]
"Exchange Ratio" = [
    "x quantity",
    "10 pounds",
]
"Good Name" = "Tea"

[["Good A"]]
"Exchange Ratio" = [
    "x quantity",
    "1 quarter",
]
"Good Name" = "Wheat"

[["Good A"]]
"Exchange Ratio" = [
    "x quantity",
    "1 piece",
]
"Good Name" = "Shirt"

[["Good A"]]
"Exchange Ratio" = [
    "x quantity",
    "2 ounces",
]
"Good Name" = "Gold"

[["Good A"]]
"Exchange Ratio" = [
    "x quantity",
    "40 pounds",
]
"Good Name" = "Coffee"

[["Good A"]]
"Exchange Ratio" = [
    "x quantity",
    "20 yards",
]
"Good Name" = "Linen"

[[Shirt]]
"Exchange Ratio" = [
    "1 piece",
    "1/2 ton",
]
"Good Name" = "Iron"

[[Shirt]]
"Exchange Ratio" = [
    "1 piece",
    "10 pounds",
]
"Good Name" = "Tea"

[[Shirt]]
"Exchange Ratio" = [
    "1 piece",
    "1 quarter",
]
"Good Name" = "Wheat"

[[Shirt]]
"Exchange Ratio" = [
    "1 piece",
    "x quantity",
]
"Good Name" = "Good A"

[[Shirt]]
"Exchange Ratio" = [
    "1 piece",
    "2 ounces",
]
"Good Name" = "Gold"

[[Shirt]]
"Exchange Ratio" = [
    "1 piece",
    "40 pounds",
]
"Good Name" = "Coffee"

[[Shirt]]
"Exchange Ratio" = [
    "1 piece",
    "20 yards",
]
"Good Name" = "Linen"

[[Gold]]
"Exchange Ratio" = [
    "2 ounces",
    "1/2 ton",
]
"Good Name" = "Iron"

[[Gold]]
"Exchange Ratio" = [
    "2 ounces",
    "10 pounds",
]
"Good Name" = "Tea"

[[Gold]]
"Exchange Ratio" = [
    "2 ounces",
    "1 quarter",
]
"Good Name" = "Wheat"

[[Gold]]
"Exchange Ratio" = [
    "2 ounces",
    "x quantity",
]
"Good Name" = "Good A"

[[Gold]]
"Exchange Ratio" = [
    "2 ounces",
    "1 piece",
]
"Good Name" = "Shirt"

[[Gold]]
"Exchange Ratio" = [
    "2 ounces",
    "40 pounds",
]
"Good Name" = "Coffee"

[[Gold]]
"Exchange Ratio" = [
    "2 ounces",
    "20 yards",
]
"Good Name" = "Linen"

[[Coffee]]
"Exchange Ratio" = [
    "40 pounds",
    "1/2 ton",
]
"Good Name" = "Iron"

[[Coffee]]
"Exchange Ratio" = [
    "40 pounds",
    "10 pounds",
]
"Good Name" = "Tea"

[[Coffee]]
"Exchange Ratio" = [
    "40 pounds",
    "1 quarter",
]
"Good Name" = "Wheat"

[[Coffee]]
"Exchange Ratio" = [
    "40 pounds",
    "x quantity",
]
"Good Name" = "Good A"

[[Coffee]]
"Exchange Ratio" = [
    "40 pounds",
    "1 piece",
]
"Good Name" = "Shirt"

[[Coffee]]
"Exchange Ratio" = [
    "40 pounds",
    "2 ounces",
]
"Good Name" = "Gold"

[[Coffee]]
"Exchange Ratio" = [
    "40 pounds",
    "20 yards",
]
"Good Name" = "Linen"

[[Linen]]
"Exchange Ratio" = [
    "20 yards",
    "1/2 ton",
]
"Good Name" = "Iron"

[[Linen]]
"Exchange Ratio" = [
    "20 yards",
    "10 pounds",
]
"Good Name" = "Tea"

[[Linen]]
"Exchange Ratio" = [
    "20 yards",
    "1 quarter",
]
"Good Name" = "Wheat"

[[Linen]]
"Exchange Ratio" = [
    "20 yards",
    "x quantity",
]
"Good Name" = "Good A"

[[Linen]]
"Exchange Ratio" = [
    "20 yards",
    "1 piece",
]
"Good Name" = "Shirt"

[[Linen]]
"Exchange Ratio" = [
    "20 yards",
    "2 ounces",
]
"Good Name" = "Gold"

[[Linen]]
"Exchange Ratio" = [
    "20 yards",
    "40 pounds",
]
"Good Name" = "Coffee"

