[["麻布"]]
"交换比例" = [
    "20码",
    "1件",
]
"产品名称" = "上衣"

[["麻布"]]
"交换比例" = [
    "20码",
    "40磅",
]
"产品名称" = "咖啡"

[["麻布"]]
"交换比例" = [
    "20码",
    "x量",
]
"产品名称" = "商品A"

[["麻布"]]
"交换比例" = [
    "20码",
    "1夸特",
]
"产品名称" = "小麦"

[["麻布"]]
"交换比例" = [
    "20码",
    "10磅",
]
"产品名称" = "茶叶"

[["麻布"]]
"交换比例" = [
    "20码",
    "2盎司",
]
"产品名称" = "金"

[["麻布"]]
"交换比例" = [
    "20码",
    "1/2吨",
]
"产品名称" = "铁"

[["上衣"]]
"交换比例" = [
    "1件",
    "20码",
]
"产品名称" = "麻布"

[["上衣"]]
"交换比例" = [
    "1件",
    "20码",
]
"产品名称" = "麻布"

[["上衣"]]
"交换比例" = [
    "1件",
    "40磅",
]
"产品名称" = "咖啡"

[["上衣"]]
"交换比例" = [
    "1件",
    "20码",
]
"产品名称" = "麻布"

[["上衣"]]
"交换比例" = [
    "1件",
    "x量",
]
"产品名称" = "商品A"

[["上衣"]]
"交换比例" = [
    "1件",
    "20码",
]
"产品名称" = "麻布"

[["上衣"]]
"交换比例" = [
    "1件",
    "1夸特",
]
"产品名称" = "小麦"

[["上衣"]]
"交换比例" = [
    "1件",
    "20码",
]
"产品名称" = "麻布"

[["上衣"]]
"交换比例" = [
    "1件",
    "10磅",
]
"产品名称" = "茶叶"

[["上衣"]]
"交换比例" = [
    "1件",
    "20码",
]
"产品名称" = "麻布"

[["上衣"]]
"交换比例" = [
    "1件",
    "2盎司",
]
"产品名称" = "金"

[["上衣"]]
"交换比例" = [
    "1件",
    "20码",
]
"产品名称" = "麻布"

[["上衣"]]
"交换比例" = [
    "1件",
    "1/2吨",
]
"产品名称" = "铁"

[["麻布"]]
"交换比例" = [
    "20码",
    "1件",
]
"产品名称" = "上衣"

[["麻布"]]
"交换比例" = [
    "20码",
    "40磅",
]
"产品名称" = "咖啡"

[["麻布"]]
"交换比例" = [
    "20码",
    "x量",
]
"产品名称" = "商品A"

[["麻布"]]
"交换比例" = [
    "20码",
    "1夸特",
]
"产品名称" = "小麦"

[["麻布"]]
"交换比例" = [
    "20码",
    "10磅",
]
"产品名称" = "茶叶"

[["麻布"]]
"交换比例" = [
    "20码",
    "2盎司",
]
"产品名称" = "金"

[["麻布"]]
"交换比例" = [
    "20码",
    "1/2吨",
]
"产品名称" = "铁"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "20码",
]
"产品名称" = "麻布"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "1件",
]
"产品名称" = "上衣"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "20码",
]
"产品名称" = "麻布"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "20码",
]
"产品名称" = "麻布"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "x量",
]
"产品名称" = "商品A"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "20码",
]
"产品名称" = "麻布"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "1夸特",
]
"产品名称" = "小麦"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "20码",
]
"产品名称" = "麻布"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "10磅",
]
"产品名称" = "茶叶"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "20码",
]
"产品名称" = "麻布"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "2盎司",
]
"产品名称" = "金"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "20码",
]
"产品名称" = "麻布"

[["咖啡"]]
"交换比例" = [
    "40磅",
    "1/2吨",
]
"产品名称" = "铁"

[["麻布"]]
"交换比例" = [
    "20码",
    "1件",
]
"产品名称" = "上衣"

[["麻布"]]
"交换比例" = [
    "20码",
    "40磅",
]
"产品名称" = "咖啡"

[["麻布"]]
"交换比例" = [
    "20码",
    "x量",
]
"产品名称" = "商品A"

[["麻布"]]
"交换比例" = [
    "20码",
    "1夸特",
]
"产品名称" = "小麦"

[["麻布"]]
"交换比例" = [
    "20码",
    "10磅",
]
"产品名称" = "茶叶"

[["麻布"]]
"交换比例" = [
    "20码",
    "2盎司",
]
"产品名称" = "金"

[["麻布"]]
"交换比例" = [
    "20码",
    "1/2吨",
]
"产品名称" = "铁"

[["商品A"]]
"交换比例" = [
    "x量",
    "20码",
]
"产品名称" = "麻布"

[["商品A"]]
"交换比例" = [
    "x量",
    "1件",
]
"产品名称" = "上衣"

[["商品A"]]
"交换比例" = [
    "x量",
    "20码",
]
"产品名称" = "麻布"

[["商品A"]]
"交换比例" = [
    "x量",
    "40磅",
]
"产品名称" = "咖啡"

[["商品A"]]
"交换比例" = [
    "x量",
    "20码",
]
"产品名称" = "麻布"

[["商品A"]]
"交换比例" = [
    "x量",
    "20码",
]
"产品名称" = "麻布"

[["商品A"]]
"交换比例" = [
    "x量",
    "1夸特",
]
"产品名称" = "小麦"

[["商品A"]]
"交换比例" = [
    "x量",
    "20码",
]
"产品名称" = "麻布"

[["商品A"]]
"交换比例" = [
    "x量",
    "10磅",
]
"产品名称" = "茶叶"

[["商品A"]]
"交换比例" = [
    "x量",
    "20码",
]
"产品名称" = "麻布"

[["商品A"]]
"交换比例" = [
    "x量",
    "2盎司",
]
"产品名称" = "金"

[["商品A"]]
"交换比例" = [
    "x量",
    "20码",
]
"产品名称" = "麻布"

[["商品A"]]
"交换比例" = [
    "x量",
    "1/2吨",
]
"产品名称" = "铁"

[["麻布"]]
"交换比例" = [
    "20码",
    "1件",
]
"产品名称" = "上衣"

[["麻布"]]
"交换比例" = [
    "20码",
    "40磅",
]
"产品名称" = "咖啡"

[["麻布"]]
"交换比例" = [
    "20码",
    "x量",
]
"产品名称" = "商品A"

[["麻布"]]
"交换比例" = [
    "20码",
    "1夸特",
]
"产品名称" = "小麦"

[["麻布"]]
"交换比例" = [
    "20码",
    "10磅",
]
"产品名称" = "茶叶"

[["麻布"]]
"交换比例" = [
    "20码",
    "2盎司",
]
"产品名称" = "金"

[["麻布"]]
"交换比例" = [
    "20码",
    "1/2吨",
]
"产品名称" = "铁"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "20码",
]
"产品名称" = "麻布"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "1件",
]
"产品名称" = "上衣"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "20码",
]
"产品名称" = "麻布"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "40磅",
]
"产品名称" = "咖啡"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "20码",
]
"产品名称" = "麻布"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "x量",
]
"产品名称" = "商品A"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "20码",
]
"产品名称" = "麻布"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "20码",
]
"产品名称" = "麻布"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "10磅",
]
"产品名称" = "茶叶"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "20码",
]
"产品名称" = "麻布"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "2盎司",
]
"产品名称" = "金"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "20码",
]
"产品名称" = "麻布"

[["小麦"]]
"交换比例" = [
    "1夸特",
    "1/2吨",
]
"产品名称" = "铁"

[["麻布"]]
"交换比例" = [
    "20码",
    "1件",
]
"产品名称" = "上衣"

[["麻布"]]
"交换比例" = [
    "20码",
    "40磅",
]
"产品名称" = "咖啡"

[["麻布"]]
"交换比例" = [
    "20码",
    "x量",
]
"产品名称" = "商品A"

[["麻布"]]
"交换比例" = [
    "20码",
    "1夸特",
]
"产品名称" = "小麦"

[["麻布"]]
"交换比例" = [
    "20码",
    "10磅",
]
"产品名称" = "茶叶"

[["麻布"]]
"交换比例" = [
    "20码",
    "2盎司",
]
"产品名称" = "金"

[["麻布"]]
"交换比例" = [
    "20码",
    "1/2吨",
]
"产品名称" = "铁"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "20码",
]
"产品名称" = "麻布"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "1件",
]
"产品名称" = "上衣"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "20码",
]
"产品名称" = "麻布"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "40磅",
]
"产品名称" = "咖啡"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "20码",
]
"产品名称" = "麻布"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "x量",
]
"产品名称" = "商品A"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "20码",
]
"产品名称" = "麻布"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "1夸特",
]
"产品名称" = "小麦"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "20码",
]
"产品名称" = "麻布"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "20码",
]
"产品名称" = "麻布"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "2盎司",
]
"产品名称" = "金"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "20码",
]
"产品名称" = "麻布"

[["茶叶"]]
"交换比例" = [
    "10磅",
    "1/2吨",
]
"产品名称" = "铁"

[["麻布"]]
"交换比例" = [
    "20码",
    "1件",
]
"产品名称" = "上衣"

[["麻布"]]
"交换比例" = [
    "20码",
    "40磅",
]
"产品名称" = "咖啡"

[["麻布"]]
"交换比例" = [
    "20码",
    "x量",
]
"产品名称" = "商品A"

[["麻布"]]
"交换比例" = [
    "20码",
    "1夸特",
]
"产品名称" = "小麦"

[["麻布"]]
"交换比例" = [
    "20码",
    "10磅",
]
"产品名称" = "茶叶"

[["麻布"]]
"交换比例" = [
    "20码",
    "2盎司",
]
"产品名称" = "金"

[["麻布"]]
"交换比例" = [
    "20码",
    "1/2吨",
]
"产品名称" = "铁"

[["金"]]
"交换比例" = [
    "2盎司",
    "20码",
]
"产品名称" = "麻布"

[["金"]]
"交换比例" = [
    "2盎司",
    "1件",
]
"产品名称" = "上衣"

[["金"]]
"交换比例" = [
    "2盎司",
    "20码",
]
"产品名称" = "麻布"

[["金"]]
"交换比例" = [
    "2盎司",
    "40磅",
]
"产品名称" = "咖啡"

[["金"]]
"交换比例" = [
    "2盎司",
    "20码",
]
"产品名称" = "麻布"

[["金"]]
"交换比例" = [
    "2盎司",
    "x量",
]
"产品名称" = "商品A"

[["金"]]
"交换比例" = [
    "2盎司",
    "20码",
]
"产品名称" = "麻布"

[["金"]]
"交换比例" = [
    "2盎司",
    "1夸特",
]
"产品名称" = "小麦"

[["金"]]
"交换比例" = [
    "2盎司",
    "20码",
]
"产品名称" = "麻布"

[["金"]]
"交换比例" = [
    "2盎司",
    "10磅",
]
"产品名称" = "茶叶"

[["金"]]
"交换比例" = [
    "2盎司",
    "20码",
]
"产品名称" = "麻布"

[["金"]]
"交换比例" = [
    "2盎司",
    "20码",
]
"产品名称" = "麻布"

[["金"]]
"交换比例" = [
    "2盎司",
    "1/2吨",
]
"产品名称" = "铁"

[["麻布"]]
"交换比例" = [
    "20码",
    "1件",
]
"产品名称" = "上衣"

[["麻布"]]
"交换比例" = [
    "20码",
    "40磅",
]
"产品名称" = "咖啡"

[["麻布"]]
"交换比例" = [
    "20码",
    "x量",
]
"产品名称" = "商品A"

[["麻布"]]
"交换比例" = [
    "20码",
    "1夸特",
]
"产品名称" = "小麦"

[["麻布"]]
"交换比例" = [
    "20码",
    "10磅",
]
"产品名称" = "茶叶"

[["麻布"]]
"交换比例" = [
    "20码",
    "2盎司",
]
"产品名称" = "金"

[["麻布"]]
"交换比例" = [
    "20码",
    "1/2吨",
]
"产品名称" = "铁"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "20码",
]
"产品名称" = "麻布"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "1件",
]
"产品名称" = "上衣"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "20码",
]
"产品名称" = "麻布"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "40磅",
]
"产品名称" = "咖啡"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "20码",
]
"产品名称" = "麻布"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "x量",
]
"产品名称" = "商品A"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "20码",
]
"产品名称" = "麻布"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "1夸特",
]
"产品名称" = "小麦"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "20码",
]
"产品名称" = "麻布"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "10磅",
]
"产品名称" = "茶叶"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "20码",
]
"产品名称" = "麻布"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "2盎司",
]
"产品名称" = "金"

[["铁"]]
"交换比例" = [
    "1/2吨",
    "20码",
]
"产品名称" = "麻布"

