[["麻布"]]
"产品名称" = "上衣"
"交换比例" = ["20码", "1件"]

[["麻布"]]
"产品名称" = "茶叶"
"交换比例" = ["20码", "10磅"]

[["麻布"]]
"产品名称" = "咖啡"
"交换比例" = ["20码", "40磅"]

[["麻布"]]
"产品名称" = "小麦"
"交换比例" = ["20码", "1夸特"]

[["麻布"]]
"产品名称" = "金"
"交换比例" = ["20码", "2盎司"]

[["麻布"]]
"产品名称" = "铁"
"交换比例" = ["20码", "1/2吨"]