[["麻布"]]
"产品名称" = "金"
"交换比例" = ["20码", "2盎司"]

[["麻布"]]
"产品名称" = "银"
"交换比例" = ["20码", "32盎司"]

[["上衣"]]
"产品名称" = "金"
"交换比例" = ["1件", "2盎司"]

[["上衣"]]
"产品名称" = "银"
"交换比例" = ["1件", "32盎司"]

[["茶叶"]]
"产品名称" = "金"
"交换比例" = ["10磅", "2盎司"]

[["茶叶"]]
"产品名称" = "银"
"交换比例" = ["10磅", "32盎司"]

[["咖啡"]]
"产品名称" = "金"
"交换比例" = ["40磅", "2盎司"]

[["咖啡"]]
"产品名称" = "银"
"交换比例" = ["40磅", "32盎司"]

[["小麦"]]
"产品名称" = "金"
"交换比例" = ["1夸特", "2盎司"]

[["小麦"]]
"产品名称" = "银"
"交换比例" = ["1夸特", "32盎司"]

[["铁"]]
"产品名称" = "金"
"交换比例" = ["1/2吨", "2盎司"]

[["铁"]]
"产品名称" = "银"
"交换比例" = ["1/2吨", "32盎司"]

[["商品A"]]
"产品名称" = "金"
"交换比例" = ["x量", "2盎司"]

[["商品A"]]
"产品名称" = "银"
"交换比例" = ["x量", "32盎司"]

[["银"]]
"产品名称" = "金"
"交换比例" = ["32盎司", "2盎司"]

[["金"]]
"产品名称" = "银"
"交换比例" = ["2盎司", "32盎司"]
