[["Linen"]]
"Good Name" = "Gold"
"Exchange Ratio" = ["20 yards", "2 ounces"]

[["Shirt"]]
"Good Name" = "Gold"
"Exchange Ratio" = ["1 piece", "2 ounces"]

[["Tea"]]
"Good Name" = "Gold"
"Exchange Ratio" = ["10 pounds", "2 ounces"]

[["Coffee"]]
"Good Name" = "Gold"
"Exchange Ratio" = ["40 pounds", "2 ounces"]

[["Wheat"]]
"Good Name" = "Gold"
"Exchange Ratio" = ["1 quarter", "2 ounces"]

[["Iron"]]
"Good Name" = "Gold"
"Exchange Ratio" = ["1/2 ton", "2 ounces"]

[["Good A"]]
"Good Name" = "Gold"
"Exchange Ratio" = ["x quantity", "2 ounces"]
