[["Linen"]]
"Good Name" = "Shirt"
"Exchange Ratio" = ["20 yards", "1 piece"]

[["Linen"]]
"Good Name" = "Tea"
"Exchange Ratio" = ["20 yards", "10 pounds"]

[["Linen"]]
"Good Name" = "Coffee"
"Exchange Ratio" = ["20 yards", "40 pounds"]

[["Linen"]]
"Good Name" = "Wheat"
"Exchange Ratio" = ["20 yards", "1 quarter"]

[["Linen"]]
"Good Name" = "Gold"
"Exchange Ratio" = ["20 yards", "2 ounces"]

[["Linen"]]
"Good Name" = "Iron"
"Exchange Ratio" = ["20 yards", "1/2 ton"]
